### ISSUE TITLE
vmapped `<c-k>` selects whole buffer

### ISSUE THREAD

**Issue by geoffharcourt** [christoomey/vim-quicklink#13]
I haven't tracked down what it is in my configuration that is conflicting with the plugin, but I am able to recreate this issue in both Vim and Neovim. When I select the word `thoughtbot` in a Markdown file in visual mode and press `<C-k>`, the suggestion at the prompt ends up being the entire buffer rather than the selected word.

**Comment by christoomey** [comment]
Do you have anything mapped to `gv` in normal mode? That's the hack I'm using to get the visual selection, specifically `gv"vy` so "re-visual-select, then yank into v register". `:verbose nnoremap gv` to check (assuming you know that, but for completeness sake).

https://github.com/christoomey/vim-quicklink/blob/master/ftplugin/markdown/quicklink.vim#L17

**Comment by geoffharcourt** [comment]
Yes, that's definitely the case. Maybe we can try using `execute normal!` to avoid existing mappings? I will fool around with it and do a PR. Thanks figuring out what was going on.
