### ISSUE TITLE
Wouldn't this be a ftplugin ?

### ISSUE THREAD

**Issue by sim590** [christoomey/vim-quicklink#5]
I was using [ultisnips](https://github.com/SirVer/ultisnips) in C++ file and `c-k` vmap began to pull a link from google, when I wanted to jump to another placeholder in ultisnips snippets. Since this plugin is made for markdown files, why isn't it a **ftplugin** ?

**Comment by christoomey** [comment]
Hello @sim590, totally valid point. I extracted this from my vimrc and a `plugin/` file was what came to mind, but you're right this should be in `ftplugin/`. Feel free to implement and submit a PR, or I'll likely get around to updating at some point.

**Comment by christoomey** [comment]
This change was implemented in https://github.com/christoomey/vim-quicklink/pull/6
